# Generated by Django 3.1.3 on 2020-12-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201203_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='id_materia',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='id_profesor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.profesor'),
        ),
    ]
